// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZNIGl5aadxxQ90bAL2Y15SDi0xEbiJQ',
    appId: '1:635865919482:web:ce2d9e6b69617c1fb5be43',
    messagingSenderId: '635865919482',
    projectId: 'push-notification-28640',
    authDomain: 'push-notification-28640.firebaseapp.com',
    storageBucket: 'push-notification-28640.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk327-aV1XMb6PCBohjYrWfWieVTRKkQc',
    appId: '1:635865919482:android:76a196ea5b119363b5be43',
    messagingSenderId: '635865919482',
    projectId: 'push-notification-28640',
    storageBucket: 'push-notification-28640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73jaGO1_dnTz0hSJp9P6ZJT3YIRws6G8',
    appId: '1:635865919482:ios:8871bd05ed7e825fb5be43',
    messagingSenderId: '635865919482',
    projectId: 'push-notification-28640',
    storageBucket: 'push-notification-28640.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73jaGO1_dnTz0hSJp9P6ZJT3YIRws6G8',
    appId: '1:635865919482:ios:45fac402761f037eb5be43',
    messagingSenderId: '635865919482',
    projectId: 'push-notification-28640',
    storageBucket: 'push-notification-28640.appspot.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
